services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: visual-sdu-app
    restart: unless-stopped

    env_file:
      - .env.test

    environment:
      SPRING_PROFILES_ACTIVE: test
      TZ: Asia/Shanghai
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Shanghai"

    depends_on:
      - mysql
      - redis

    ports:
      - "127.0.0.1:8080:8080"


  mysql:
    image: mysql:8.4

    container_name: visual-sdu-mysql
    restart: unless-stopped

    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: vsdu-db
      MYSQL_USER: ${VSDU_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${VSDU_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    command:
      - --default-time-zone=+08:00

    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro


  redis:
    image: redis:8-alpine

    container_name: visual-sdu-redis
    restart: unless-stopped

    environment:
      TZ: Asia/Shanghai

    command:
      - redis-server
      - --appendonly
      - "yes"
      - --requirepass
      - "${VSDU_REDIS_PASSWORD}"

    volumes:
      - redis-data:/data

  frpc:
    image: snowdreamtech/frpc:latest
    container_name: visual-sdu-frpc
    restart: unless-stopped

    volumes:
      - ./frpc.toml:/etc/frp/frpc.toml:ro

    depends_on:
      - app


volumes:
  mysql-data:
  redis-data:
