spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vsdu-db
    username: root
    password: ${LOCAL_MYSQL_PASSWORD}

  data:
    redis:
      host: 8.130.108.118
      port: 16379
      password: ${VSDU_REDIS_PASSWORD}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

vsdu:
  auth:
    frontend-return-url: https://localhost:5173/auth/return

