spring:
  application:
    name: visual-sdu

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 120MB

server:
  forward-headers-strategy: native

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: cn.sduonline.business.data.po
  configuration:
    map-underscore-to-camel-case: true

vsdu:
  jwt:
    sdupass:
      sdu-pass-secret: ${SDU_PASS_SECRET}
      salt: KOISHIKISHIKAWAIIKAWAIIKISSKISSLOVELY
      iteration-cound: 114514
      key-length: 256

    local:
      local-secret: ${JWT_SECRET}
      access-token-expire-seconds: 3600
      refresh-token-expire-seconds: 604800

logging:
  pattern:
    level: "%5p [traceId=%X{traceId:-N/A}] [ip=%X{ip:-N/A}]"

cloudflare:
  r2:
    endpoint: https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com
    access-key-id: ${R2_ACCESS_KEY_ID}
    secret-access-key: ${R2_SECRET_ACCESS_KEY}
    bucket: vsdu-bucket